### ISSUE TITLE
It would be more convenient if we have a python library for it

### ISSUE THREAD

**Issue by owaski** [XapaJIaMnu/gLM#4]
It would be more convenient if we have a python library for it

**Comment by XapaJIaMnu** [comment]
Hey @owaski ,

Thank you for your interest in the project.

 I started doing a python interface, and there is a working version of it (Provided you use CUDA 7.0). I have one exported function here: https://github.com/XapaJIaMnu/gLM/blob/master/gpu/nematus_ngrams.hh#L252 
As it never quite delivered better performance than a neural network language, I never finished the work. At this point in time, since ngram language models are largely out of fashion, I don't intend to work on this project anymore. I am happy to accept new contributions, though.

Cheers,

Nick

**Comment by owaski** [comment]
Thanks for your response!
I'll consider alternative options.
